AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  HonoLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs20.x
      CodeUri: .
      Environment:
        Variables:
          AWS_ENDPOINT: ${AWS_ENDPOINT}
          AWS_REGION: ${AWS_REGION}
          AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
          AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
          S3_BUCKET: ${S3_BUCKET}
      Events:
        Root:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        GenerateUrl:
          Type: Api
          Properties:
            Path: /generate-url
            Method: ANY
